stages:
  - build
  - test
  - deploy 
variables:
  CMAKE_BUILD_PARALLEL_LEVEL: 4
before_script:
  - git submodule sync
  - git submodule update --init --recursive
  
include:
  - .ci/linux.yml
  - .ci/windows.yml
  - .ci/macos.yml
