name: libtusclient CI Linux

on:
  push:
  pull_request:
  release:
    types: [created]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        c_compiler: [gcc]
        include:
          - c_compiler: gcc
            cpp_compiler: g++
            conan_home: /home/runner/.conan2
            conan_profile: /home/runner/.conan2/profiles/default

    steps:
      - uses: actions/checkout@v4

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "build-type=release" >> "$GITHUB_OUTPUT"
            echo "test-folder=Release" >> "$GITHUB_OUTPUT"
          else
            echo "build-type=debug" >> "$GITHUB_OUTPUT"
            echo "test-folder=Debug" >> "$GITHUB_OUTPUT"
          fi

      - name: Install conan package manager
        run: |
          pip install conan
          conan --version

      - name: Cache .conan
        uses: actions/cache@v3
        with:
          path: ${{ matrix.conan_home }}
          key: ${{ runner.os }}-conan-${{ matrix.c_compiler }}-${{ steps.strings.outputs.build-type }}
          restore-keys: |
            ${{ runner.os }}-conan-${{ matrix.c_compiler }}-

      - name: Create Conan profiles
        continue-on-error: true
        run: |
          conan profile detect

      - name: Conan profile setup
        run: |
          sed -i 's/^build_type=.*/build_type=${{ steps.strings.outputs.test-folder }}/g' ${{ matrix.conan_profile }}

      - name: Install dependencies
        run: |
          conan install . --build=missing --profile=default

      - name: Configure CMake
        run: cmake --preset conan-${{ steps.strings.outputs.build-type }}

      - name: Build Library
        run: cmake --build --preset conan-${{ steps.strings.outputs.build-type }} --target libtusclient

      - name: Build Tests
        run: cmake --build --preset conan-${{ steps.strings.outputs.build-type }} --target libtusclient_test

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts-linux
          path: ${{ github.workspace }}/build/${{ steps.strings.outputs.test-folder }}/libtusclient.so
      - name: Upload artifacts for test
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts-for-test
          path: |
            ${{ github.workspace }}/build/Debug/liblibtusclient.so
            ${{ github.workspace }}/build/Debug/test/libtusclient_test

  test-linux:
    needs: build-linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: "Create folder for test results"
        run: mkdir -p ${{ github.workspace }}/build/Debug
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts-for-test
          path: ${{ github.workspace }}/build/Debug

      - name: Run Mockoon CLI
        uses: mockoon/cli-action@v2
        with:
          version: "latest"
          data-file: "./mockoon-data.json"
          port: 3000

      - name: Docker TUSD
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: docker run -d -p 8080:8080 tusproject/tusd:latest

      - name: Test Project
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          chmod +x ${{ github.workspace }}/build/Debug/test/libtusclient_test
          export LD_LIBRARY_PATH=${{ github.workspace }}/build/Debug:$LD_LIBRARY_PATH
          ldd ${{ github.workspace }}/build/Debug/test/libtusclient_test
          ${{ github.workspace }}/build/Debug/test/libtusclient_test --gtest_output=xml:${{ github.workspace }}/build/Debug/test-results.xml
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ${{ github.workspace }}/build/Debug/test-results.xml

 
  release-linux:
    needs: test-linux
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: ${{ github.workspace }}/build/${{ steps.strings.outputs.test-folder }}

      - name: Upload Release Artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ github.workspace }}/build/${{ steps.strings.outputs.test-folder }}
          asset_name: libtusclient-${{ steps.strings.outputs.build-type }}.zip
          asset_content_type: application/zip
